apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  labels:
    app: cad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cad
  template:
    metadata:
      labels:
        app: cad
    spec:
      containers:
      - name: cadvisor
        image: google/cadvisor:latest
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
        - name: var-run
          mountPath: /var/run
        - name: sys
          mountPath: /sys
        - name: var-lib-docker
          mountPath: /var/lib/docker
        - name: dev-disk
          mountPath: /dev/disk
        ports:
        - containerPort: 8080
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: var-lib-docker
        hostPath:
          path: /var/lib/docker
      - name: dev-disk
        hostPath:
          path: /dev/disk
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cad-service
spec:
  selector:
    app: cad
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
