apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-frontend
  labels:
    app: flask 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-web-frontend
        image: 301989/flask-web-container:v3
        ports:
        - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-web-ext-service
spec:
  selector:
    app: flask
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      