apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheous-yml
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'node_exporter'
      static_configs:
      - targets: ['node-exp-int-service:9100']
    - job_name: 'cadvisor'
      static_configs:
      - targets: ['cad-service:8080']
