apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-app
  labels:
    app: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - name: prom
        image: prom/prometheus:latest
        volumeMounts:
        - name:  prom-config
          mountPath: /etc/prometheus
        ports:
        - containerPort: 9090
      volumes:
      - name: prom-config
        configMap:
          name: prometheous-yml
      restartPolicy: Always
---
apiVersion: v1
kind: Service 
metadata:
  name: prom-ext-service 
spec:
  selector:
    app: prom
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: prom-int-service
spec:
  selector:
    app: prom 
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
